skip_commits:
  message: /Updated (readme|docs).*|!skipci/

image: Visual Studio 2019

clone_folder: C:\BNMoldovaCurrency

environment:
  NugetApiKey:
    secure: BzmlXiDeaTtssidQVqDbsyel84wxxlkqdlzw5JjuYfPaHEbUert5OC6lvD+D7yB4

cache:
  - _build_dependencies_ -> *.Depend.psd1

build: off

build_script:
  - ps: '& .\build.ps1 -Task Build'

test_script:
  - ps: '& .\build.ps1 -Task Test'

deploy_script:
  - ps: '& .\build.ps1 -Task Deploy'

after_build:
  - ps: 7z a output.zip output

on_finish:
  - ps: Get-ChildItem -Filter 'output.zip' | % { Push-AppveyorArtifact $_.FullName }